In [3]:
import pandas as pd
import numpy as np

# 读取CSV文件
file_path = 'extracted_line_data.csv'
data = pd.read_csv(file_path)

# 提取 'Exact Bus1' 和 'Exact Bus2' 列的唯一值并生成索引字典
unique_values = pd.concat([data['Exact Bus1'], data['Exact Bus2']]).drop_duplicates().tolist()
value_dict = {value: idx for idx, value in enumerate(unique_values)}

# 初始化邻接矩阵
n = len(value_dict)  # 唯一值的数量决定矩阵大小
adj_matrix = np.zeros((n, n), dtype=int)

# 遍历每一行并更新邻接矩阵
for _, row in data.iterrows():
    idx1 = value_dict[row['Exact Bus1']]
    idx2 = value_dict[row['Exact Bus2']]
    adj_matrix[idx1, idx2] = 1  # 设置连接关系
    adj_matrix[idx2, idx1] = 1  # 矩阵对称

# 打印邻接矩阵
print("邻接矩阵 A:")
print(adj_matrix)
adj_matrix.shape


邻接矩阵 A:
[[0 1 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(123, 123)

In [4]:
import numpy as np

# 假设邻接矩阵 adj_matrix 已经生成
# 提取非零元素的行和列索引
rows, cols = np.where(adj_matrix == 1)

# 避免重复（由于无向图，A[i, j] 和 A[j, i] 是对称的）
edges = set()
for r, c in zip(rows, cols):
    if r < c:  # 确保只添加一次 (i, j)，避免重复
        edges.add((r, c))

# 转换为 numpy 数组
edge_list = np.array(list(edges)).T  # 转置为 2 × N 格式

# 打印结果
print("边列表（Edge List）:")
print(edge_list)
edge_list.shape

边列表（Edge List）:
[[ 55  72  24  44  16  40  63  56   7  41  59  18  25  14  20  12  74   5
   15  13   7  35  42  14  48   9  75  27  12   5  22  77  48  49  13  44
   45  55  47  78  51  46  22  23  57  39  73  72  50  52  74  53  53   8
   30  25  26  31  17  10  27  37  54   1  28  64   6  15   5  51  60  38
   29   1  33   9   2  32  29  61  44   1   2  62  67  58  35  44  68  19
   11  60   4  43  59  69  26   0  76  10  65   8  36  37  33  61  69  70
   22  39  34   3  66  62  23  71  76   9]
 [ 57  73  97  45  93  41 116 110  10  42 112  19  98  15  95  91  75  85
   16  92  21  37  43  17  49  21  76  29  13   7  23  78  51  50  14  81
   46  56 107 122  52  47  25  24 111 105 119  74 108  53 120 109  54  86
   31  26  27  32  18  12  28  39  55  82 100  65   8  20   6  58  61 104
  101   2  80  89  83 102  30  62  64   4   3  63 117  59  36  48  69  94
   90 113   5 106  60  70  99   1 121  11  66  87 103  38  34 114  72  71
   79  40  35  84  67 115  96 118  77  88]]


(2, 118)